import { z } from "zod";

export const formSchema = z.object({
  carteirinha: z.string().min(1, "Campo obrigatório"),
  nomeCompleto: z.string().min(1, "Campo obrigatório"),
  dataNascimento: z.string().min(1, "Campo obrigatório"),
  numeroGestacoes: z.string().optional().default("0"),
  numeroPartosCesareas: z.string().optional().default("0"),
  numeroPartosNormais: z.string().optional().default("0"),
  numeroAbortos: z.string().optional().default("0"),
  telefones: z.string().min(1, "Campo obrigatório"),
  procedimento: z.array(z.string()).min(1, "Selecione pelo menos um procedimento"),
  dum: z.string().min(1, "Campo obrigatório"),
  dataDum: z.string().optional(),
  dataPrimeiroUsg: z.string().min(1, "Campo obrigatório"),
  semanasUsg: z.string().min(1, "Campo obrigatório"),
  diasUsg: z.string().min(1, "Campo obrigatório"),
  usgRecente: z.string().min(1, "Campo obrigatório"),
  igPretendida: z.string().min(1, "Campo obrigatório"),
  indicacaoProcedimento: z.string().min(1, "Campo obrigatório"),
  medicacao: z.string().min(1, "Campo obrigatório"),
  diagnosticosMaternos: z.array(z.string()).default([]),
  placentaPrevia: z.string().min(1, "Campo obrigatório"),
  diagnosticosFetais: z.array(z.string()).default([]),
  diagnosticosFetaisOutros: z.string().optional(),
  historiaObstetrica: z.string().min(1, "Campo obrigatório"),
  necessidadeUtiMaterna: z.string().min(1, "Campo obrigatório"),
  necessidadeReservaSangue: z.string().min(1, "Campo obrigatório"),
  maternidade: z.string().min(1, "Campo obrigatório"),
  medicoResponsavel: z.string().min(1, "Campo obrigatório"),
  centroClinico: z.string().min(1, "Campo obrigatório"),
  email: z.string().email("Email inválido").min(1, "Campo obrigatório"),
});
